### ISSUE TITLE
Hubitat Package Manager -- didn't add

### ISSUE THREAD

**Issue by kubla36** [joelwetzel/Hubitat-Switch-Bindings#8]
Hubitat Package Manager installed the app but did not add it.  I had to "+ Add user app" for it to show up.

**Comment by ebukva** [comment]
Second the above comment. Thought something was broken until I found this comment. It would be ideal if package manager installation also added the app. I’d suggest giving a heads up in the docs about that while it doesn’t.

**Comment by joelwetzel** [comment]
This is the way HPM and Hubitat work.  I will add a note in the instructions though.
